### ISSUE TITLE
When I updated to version v1.5, the pdf function did not work.

### ISSUE THREAD

**Issue by telppa** [iseahound/ImagePut#12]
When I updated to v1.5, the pdf function did not work.

If I use version of v1.3 (sorry I can't tell which version of v1.3 it is), the pdf function works fine.

I packaged a pdf file with the test code and the v1.3 library files for testing.

[pdf test.zip](https://github.com/iseahound/ImagePut/files/7832553/pdf.test.zip)

**Comment by telppa** [comment]
I also noticed that in version 1.5, the following code works fine
`imageputwindow({image:"2.pdf", scale:0.5})`

this not
`imageputwindow("2.pdf")`

**Comment by telppa** [comment]
![2](https://user-images.githubusercontent.com/68984587/148631633-1c95ff09-cdf5-47db-9d86-651897eb1b62.png)
![3](https://user-images.githubusercontent.com/68984587/148631635-66c73d20-e0ff-4939-bc2f-3eed5c3550c8.png)

**Comment by iseahound** [comment]
I've found the typo and corrected it.
