### ISSUE TITLE
Receiving "invalid UTF-8 payload" from server when sending ImagePutBase64 strings

### ISSUE THREAD

**Issue by sargearmstrong** [iseahound/ImagePut#16]
Dears,

Appreciate the library, thanks so much!

What, if any, non-UTF8 characters could ImagePutBase64 be generating in the Base64 string? Not sure if this is actually the case but..

I'm using the call below (from ImagePut for v1) and sending the output to a websocket server which works great, albeit the server randomly (and rarely) throws "invalid UTF-8 payload" which I'm struggling to catch/sanitize on the client before sending.

ImagePutBase64({image: [0, 0, A_ScreenWidth, A_ScreenHeight ], scale: ["", 600]}, "jpg", 75)

When able, kindly share whatever you deem helpful. Thank you for your time and effort!

**Comment by iseahound** [comment]
Can't say for certain what the cause is, it's clearly failing your servers
validation code. You'll have to try and figure out what the cause is,
ImagePut uses CryptBinaryToString (microsoft's implementation) so that may
help.

**Comment by sargearmstrong** [comment]
Thank you friend. Seems I jumped the gun - looks like the lack of debounce in my send function was causing packet differentiation issues, sorry.. thank you though.
