### ISSUE TITLE
pStream cannot be zero

### ISSUE THREAD

**Issue by jpuerj** [iseahound/ImagePut#23]
Hi! First of all, thank you for this amazing library, I'm having a problem when running multiple timers with `ImagePutBuffer(windowName)`. It all works fine, but suddenly, I get this message `pStream cannot be zero` after running the script for some time. In this script, I usually get images from 4 different windows and when one stop working every other stop working as well.

**Comment by iseahound** [comment]
Hi, generally using

ImagePutBuffer({window: windowname})

should fix your problem. You'd have to post some code if you'd like me to
dig further.

**Comment by jpuerj** [comment]
Okay! I'll try that, thanks!
