### ISSUE TITLE
No ImageSearchAll() in ImagePut.ahk(for v2)

### ISSUE THREAD

**Issue by DaZF** [iseahound/ImagePut#26]
At the `Release v1.9 ImagePut.ahk(for v2)` file, there has no `PixelSearchAll()` and `ImageSearchAll()`.
I can find it at the master branch.

Why not update the release version?

**Comment by DaZF** [comment]
2023-03-02T14:48:52
At the master branch `ImagePut.ahk` for ahk v2, there has some errors from lines 3762 to lines 3787.
I dont know how to fix it. This part code is different from `v1.9`.

**Comment by iseahound** [comment]
Good idea! 6a0532240b11f8094c867c1f634417ddbc32af30
