### ISSUE TITLE
webp support

### ISSUE THREAD

**Issue by aaaboypop** [iseahound/ImagePut#41]
![image](https://github.com/iseahound/ImagePut/assets/13348147/8c792246-e473-461c-9806-42211adfbf20)

**Comment by iseahound** [comment]
GDI+ should support WebP and heic (assuming you paid $1)... but I can't figure out how to get it working. 

Notes:
1. It may have something to do with setting the GDI+ version to 2. 
2. Convert from WIC and back.

**Comment by iseahound** [comment]
Solved with 85c68728ab75861760973e5aec365996a6e8fd73
