### ISSUE TITLE
I need an image window without a title bar, can it be achieved?

### ISSUE THREAD

**Issue by sanmaodo** [iseahound/ImagePut#6]
I need an image window without a title bar, can it be achieved?
<img width="310" alt="1019222412" src="https://user-images.githubusercontent.com/29154707/137930649-54291236-06d8-4ebc-9f83-08c1ab384c6d.png">

**Comment by telppa** [comment]
```
hWin := imageputwindow("1.png")
WinSet, Style, -0xC00000, ahk_id %hWin%
```

imageputwindow return window's hwnd.  so you can easily remove the title bar.

**Comment by iseahound** [comment]
Hmm... That does something weird on my system. It's actually very easy to make one without a titlebar. I specifically tried to create a window with a title bar for the ImagePutWindow function. And make the windows without titlebar part of ImageRender.

**Comment by iseahound** [comment]
If I add a window without a titlebar, what do I call this new function? ImagePutWindow is already taken.

**Comment by telppa** [comment]
ImagePutDisplay ? ImagePutShow ? or ImagePutWindow(p1, p2, notitlebar:=true) ?

**Comment by iseahound** [comment]
Alright I've decided on ImageShow(). 

    ImageShow("https://picsum.photos/200")
    ImageShow("https://picsum.photos/500", "a random pic", [500])
    ImagePutWindow("https://picsum.photos/200/300")
    ImagePut.gdiplusStartup()
    ImagePut.show(ImagePutBitmap("https://picsum.photos/100"))

It's been added to the main script, feel free to test it out. 
In addition, ImagePutWindow has been extended to include a position parameter.

**Comment by iseahound** [comment]
Function signature

    ;   title      -  Window Title            |  string   ->   MyTitle
    ;   pos        -  Window Coordinates      |  array    ->   [x,y,w,h] or [0,0]
    ;   style      -  Window Style            |  uint     ->   WS_VISIBLE
    ;   styleEx    -  Window Extended Style   |  uint     ->   WS_EX_LAYERED
    ;   parent     -  Window Parent           |  ptr      ->   hwnd
    ImageShow(image, title := "", pos := "", style := 0x10000000, styleEx := 0x80088, parent := 0) {
        return ImagePut("show", image, title, pos, style, styleEx, parent)
    }
