### ISSUE TITLE
cover pdf to jpg will get an error.

### ISSUE THREAD

**Issue by telppa** [iseahound/ImagePut#8]
here is test code, both get an error (but cover is complete ).
```
imageputfile("2.pdf", "1.jpg")

imageputfile({pdf:"2.pdf"}, {image:"1.jpg"})

```
![1](https://user-images.githubusercontent.com/68984587/145526756-7b9900de-9067-475a-b469-5a3b92783c8f.png)

**Comment by iseahound** [comment]
I am unable to reproduce this error

**Comment by telppa** [comment]
I can't reproduce the error either......

I'll reopen this when I find a way to reproduce this.
