### ISSUE TITLE
if index > pdf's total number of pages , show a more friendly error tip?

### ISSUE THREAD

**Issue by telppa** [iseahound/ImagePut#9]
`imageputfile({image:"2.pdf", index:888}, "1.jpg")
`

if pdf's total number of pages is less than 888, it will get this error.

maybe can more friendly, tell people index is too big?

![1](https://user-images.githubusercontent.com/68984587/145662313-d3b384de-b26c-48ec-a187-9884257c232a.png)

**Comment by iseahound** [comment]
![2021-12-11 21꞉05꞉24](https://user-images.githubusercontent.com/9779668/145697688-f942bad2-2062-4d76-96a7-70ccc79e3677.png)

**Comment by iseahound** [comment]
You may find ImagePutFile("A") to be a useful hotkey :)
